env:
  global:
    - CODECOV_TOKEN="5770a6c4-0717-47fd-9919-74604bd909b9" # https://codecov.io

language: node_js

node_js:
  - 10

# not required as of 2016(?)
# before_script:
#  - npm install -g grunt-cli

before_script:
  - npm install -g codecov

script:
  - npm run coverage # get the coverage run before building
  - codecov          # upload coverage reports to codecov.io
  - npm run build    # we have a build badge, so run the build
